environment:
  matrix:
    - python_version: "C:\\Python27"
      cassandra_version: 3.0.3
os: Visual Studio 2015
platform:
  - x64
install:
  - ps: .\appveyor.ps1
build_script:
  - cmd: |
      "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" x86_amd64
      python setup.py install --no-cython
test_script:
  -  ps: Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope Process -force
  -  cmd: nosetests -s -v --with-ignore-docstrings --with-xunit --xunit-file=standard_results.xml .\tests\integration\standard\test_cluster.py:ClusterTests
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
cache:
  - C:\Users\appveyor\.m2
  - C:\ProgramData\chocolatey\bin
  - C:\ProgramData\chocolatey\lib
  - C:\Users\appveyor\jce_policy-1.7.0.zip
  - C:\Users\appveyor\jce_policy-1.8.0.zip
  - C:\Users\appveyor\.ccm\repository
  - C:\Users\appveyor\ccm