environment:
  matrix:
    - python_version: 2.7.11
      PYTHON: "C:\\Python27-x64"
      cassandra_version: 3.0.3
os: Visual Studio 2015
platform:
  - x64
install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - ps: .\appveyor.ps1
build_script:
  - cmd: |
      "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" x86_amd64
      python setup.py install --no-cython
test_script:
  -  ps: .\run_test.ps1
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
cache:
  - C:\Users\appveyor\.m2
  - C:\ProgramData\chocolatey\bin
  - C:\ProgramData\chocolatey\lib
  - C:\Users\appveyor\jce_policy-1.7.0.zip
  - C:\Users\appveyor\jce_policy-1.8.0.zip
  - C:\Users\appveyor\.ccm\repository
  - C:\Users\appveyor\ccm